AjApp/Models/Auth.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AjApp.Models
{
    public class Auth
    {
        [Key]
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("email")]
        public string? Email { get; set; }
        [Column("password")]
        public string? Password { get; set; }
    }
}

AjApp/Models/AuthUser.cs
using AjApp.Models;
namespace AjApp.Models
{
    public class AuthUser
    {

        public Auth? Auth { get; set; }
        public User? User { get; set; }
    }
}

AjApp/Models/ErrorViewModel.cs
namespace AjApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AjApp/Models/User.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace AjApp.Models
{
    public class User
    {
        [Key]
        [Column("user_id")]
        public string? UserId { get; set; }
        [Column("name")]
        public string? Name { get; set; }
        [Column("following")]
        public int? Following { get; set; }
        [Column("dob")]
        public DateTime? DOB { get; set; }
        [Column("country")]
        public string? Country { get; set; }
        [Column("created_on")]
        public DateTime? CreatedOn { get; set; }
    }
}

AjApp/Controllers/AjMusicController.cs
using Microsoft.AspNetCore.Authentication.OAuth.Claims;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Runtime.InteropServices;

namespace AjApp.Controllers
{
    public class AjMusicController : Controller
    {
        [HttpGet]
        [Route("ajfy")]
        public async Task<IActionResult> Ajfy(string? query)
        {
            if (query != null)
            {
                var _sclient = new HttpClient();
                var _srequest = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://localhost:7020/ajfy/searchsong?query={query}")
                };

                try
                {
                    using var response = await _sclient.SendAsync(_srequest);
                    if (response.IsSuccessStatusCode)
                    {
                        var body = (JArray)JsonConvert.DeserializeObject(await response.Content.ReadAsStringAsync());
                        Console.WriteLine($"The body is {body}");
                        ViewBag.SearchedSong = body;
                        Console.WriteLine(body);
                        return View();
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Exception = e.Message;
                    return View();
                }
            }
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://localhost:7020/ajfy/getalltracks")
                };

            try
            {
                using var response = await client.SendAsync(request);
                if (response.IsSuccessStatusCode)
                {
                    dynamic body = (JArray)JsonConvert.DeserializeObject(await response.Content.ReadAsStringAsync());
                    ViewBag.SearchedData = body;
                    return View();
                }
            }catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }

            ViewBag.ApiDown = "API is Down! Sorry For the Inconvinence. Please try after sometime! Thank you for supporting Ajfy";
            return View();
        }
    }
}

AjApp/Controllers/AuthController.cs
using AjApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Text;

namespace AjApp.Controllers
{
    public class AuthController : Controller
    {
        [Route("signup")]
        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }


    }
}

AjApp/Controllers/HomeController.cs
using AjApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AjApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AjApp/Controllers/PlayListController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace AjApp.Controllers
{
    [Route("ajfy/playlist")]
    public class PlayListController : Controller
    {
        public async Task<IActionResult> Index(string? playlistname)
        {
            if(playlistname != null)
            {

                var _pclient = new HttpClient();
                var content = new StringContent(playlistname);
try
                {
                    using var _presponse = await _pclient.PostAsync("https://localhost:7020/ajfy/createnewplaylist", content);
                    if (_presponse.IsSuccessStatusCode)
                    {
                        Console.WriteLine("Created successfully");
                        return Redirect("https://spotify.com");
                    }
                }
                catch(Exception e)
                {
                    Console.WriteLine(e.Message);
                }

            }
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://localhost:7020/ajfy/getallplaylists"),
        };

        try
        {
                using var response = await client.SendAsync(request);
                if (response.IsSuccessStatusCode)
                {
                    dynamic body = (JArray)JsonConvert.DeserializeObject(await response.Content.ReadAsStringAsync());
                    ViewBag.PlaylistData = body;
                    Console.WriteLine(body);
                    return View();
                }
                else
                {
                    ViewBag.NoData = "No Playlist";
                    return View();
                }
        }catch(Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }


            return View();
        }
    }
}

AjApp/Views/AjMusic/Ajfy.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var SearchedSong = ViewBag.SearchedSong;
    var Exception = ViewBag.Exception;
    var ApiDown = ViewBag.ApiDown;
    var TracksData = ViewBag.SearchedData;
    Layout = null;
}

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ajfy.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AjApp.styles.css" asp-append-version="true" />
</head>

<body>

    <div class="d-flex flex-column align-items-center mt-5">
        <div class="navbar-custom d-flex flex-row align-items-lg-center justify-content-around">
            <a asp-action="Ajfy"><img src="~/dashboard.png" height="20" width="20"/></a>
            <form class="mt-3" method="get" asp-action="Ajfy">
            <input class="search data" name="query" />
            <input name="query" value="Search " class="btn-custom mx-4" type="submit"/>
            </form>
            <a asp-controller="PlayList" asp-action="Index">
            <img src="~/playlist.png" height="20" width="20"/>
            </a>
        </div>

        @if (SearchedSong != null && SearchedSong.Count != 0)
        {

            Console.WriteLine(SearchedSong);
            <div class="music-card d-flex flex-row justify-content-around align-items-center track-card m-5">
                <img src=@SearchedSong[0]["imgUrl"] width="40" height="40" class="m-2" />
                <p class="m-2 text-white">@SearchedSong[0]["title"]</p>
                <p class="m-2 text-white">@SearchedSong[0]["name"]</p>
                <audio controls>
                    <source src="@SearchedSong[0]["previewUrl"]" type="audio/mp3">
                </audio>
            </div>
        }
        @if(TracksData != null)
        {
            <div class="d-flex flex-column align-items-center">
                @foreach (var track in TracksData)
                {
                    var trackId = track["trackId"];
                        <div class="music-card d-flex flex-row justify-content-around align-items-center track-card m-5">
                            <img src=@track["imgUrl"] width="25rem" height="25rem" class="m-2" />
                            <p class="m-2 text-white">@track["title"]</p>
                            <p class="m-2 text-white">@track["name"]</p>
                            <p class="m-2 text-white"><span class="data">Duration:</span> @track["duration"] secs</p>
                <audio controls style="width=20; height=20">
                    <source src="@track["previewUrl"]" type="audio/mp3">
                </audio>
                        </div>
                }
            </div>
        }
    </div>

</body>
</html>

AjApp/Views/PlayList/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
    var PlayListData = ViewBag.PlayListData;
}

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/playlist.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AjApp.styles.css" asp-append-version="true" />
</head>

<body>
    @if(PlayListData == null)
    {
        <p class=" text-center  m-5" style="color:#ad00ff">@ViewBag.NoData :( </p>
        <p class="text-center " style="color:#ad00ff">Want to Create one?</p>
        <p class="text-center " style="color:#ad00ff">Let's Create One! Happi Happi Happi</p>
    }
    <div class="d-flex flex-column align-items-center">
    <form asp-action="Index" method="post">
        <input name="playlistname" style="border-radius:2rem"/>
        <input type="submit" name="playlistname" class="btn btn-custom btn-sm"/>
    </form>

    </div>
</body>
</html>

AjApp/Views/Shared/_Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AjApp.styles.css" asp-append-version="true" />
</head>
<body class="bg overflow-hidden">
    <section class="d-flex flex-column align-items-center">
        <div class="d-flex flex-row align-items-center m-4">
            <img src="~/WaveForm.png" width="100" height="100" class="mt-4 waveform"/>
            <h1 id="title">Ajfy</h1>
        </div>
        <div>
            <a class="btn btn-custom text-black " asp-controller="AjMusic" asp-action="Ajfy">Get Started</a>
        </div>
        <p class="mt-5 text-white">This is a Free online anonymous music streaming site. No account! No data! Just listen to Music</p>
        <p class="mt-5 text-white"><span id="note">Note:</span> The site is under construction. You can only able to play the preview of the song.</p>
    </section>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    </body>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</html>

AjApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AjApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AjApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AjApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AjApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>